### ISSUE TITLE
Implement basic tap-based functionality for buttons.

### ISSUE THREAD

**Issue by AbdallahKayed** [Project-Pixel-UoS/Brew-n-Buzz#2]

**Comment by OliviaStarStuff** [comment]
What do you mean by basic tap based functionality?

**Comment by AbdallahKayed** [comment]
Hi Olivia, this means that the code has to have tap functionality for the buttons (like make sure that the tap gestures work). We want to aim to have it work on mobile from now, instead of leaving the mobile aspects until the end.

**Comment by OliviaStarStuff** [comment]
The buttons should work as buttons as they emulate mouse input. But if you want multi touch, that has to be something we do where we need it. As it is, I don't have an android phone to test multi touch functionality.

Do we know what we want tap gestures for? Is it part of the design?
